Repository sakshi-choudhary/CoronaGo, pull requests merged in 2021-10, with the labels that each got.

#2 add box-shadow to nav
  style.css
Labels: good first issue, hactoberfest

#3 update card padding
  index.html
Labels: hactoberfest

#4 remove consoles
  script.js
Labels: documentation, hactoberfest
